-- =============================================================================
-- Landscapers Inc. HQ — Row Level Security
-- GENERATED by tools/gen-sql.mjs from js/schema/*.js — do not edit by hand.
-- =============================================================================

-- Every table: RLS enabled; anon has no access at all.
-- Owner/admin pass every check through public.has_role().

alter table public.profiles enable row level security;
revoke all on public.profiles from anon;
grant select, insert, update, delete on public.profiles to authenticated;
drop policy if exists profiles_select on public.profiles;
drop policy if exists profiles_insert on public.profiles;
drop policy if exists profiles_update on public.profiles;
drop policy if exists profiles_delete on public.profiles;
create policy profiles_select on public.profiles for select to authenticated using (auth.uid() is not null);
create policy profiles_insert on public.profiles for insert to authenticated with check (public.has_role(array[]::text[]));
create policy profiles_update on public.profiles for update to authenticated using (id = auth.uid()::text or public.has_role(array[]::text[])) with check (id = auth.uid()::text or public.has_role(array[]::text[]));
create policy profiles_delete on public.profiles for delete to authenticated using (public.has_role(array['owner']));
-- People may edit their own profile but never their own role or status (enforced by trigger in 03_triggers.sql).

alter table public.groups enable row level security;
revoke all on public.groups from anon;
grant select, insert, update, delete on public.groups to authenticated;
drop policy if exists groups_select on public.groups;
drop policy if exists groups_insert on public.groups;
drop policy if exists groups_update on public.groups;
drop policy if exists groups_delete on public.groups;
create policy groups_select on public.groups for select to authenticated using (auth.uid() is not null and public.my_role() is not null);
create policy groups_insert on public.groups for insert to authenticated with check (public.has_role(array['owner', 'admin']));
create policy groups_update on public.groups for update to authenticated using (public.has_role(array['owner', 'admin'])) with check (public.has_role(array['owner', 'admin']));
create policy groups_delete on public.groups for delete to authenticated using (public.has_role(array['owner', 'admin']));

alter table public.settings enable row level security;
revoke all on public.settings from anon;
grant select, insert, update, delete on public.settings to authenticated;
drop policy if exists settings_select on public.settings;
drop policy if exists settings_insert on public.settings;
drop policy if exists settings_update on public.settings;
drop policy if exists settings_delete on public.settings;
create policy settings_select on public.settings for select to authenticated using (auth.uid() is not null and public.my_role() is not null);
create policy settings_insert on public.settings for insert to authenticated with check (public.has_role(array['owner', 'admin']));
create policy settings_update on public.settings for update to authenticated using (public.has_role(array['owner', 'admin'])) with check (public.has_role(array['owner', 'admin']));
create policy settings_delete on public.settings for delete to authenticated using (public.has_role(array['owner', 'admin']));

alter table public.calendars enable row level security;
revoke all on public.calendars from anon;
grant select, insert, update, delete on public.calendars to authenticated;
drop policy if exists calendars_select on public.calendars;
drop policy if exists calendars_insert on public.calendars;
drop policy if exists calendars_update on public.calendars;
drop policy if exists calendars_delete on public.calendars;
create policy calendars_select on public.calendars for select to authenticated using (auth.uid() is not null and public.my_role() is not null);
create policy calendars_insert on public.calendars for insert to authenticated with check (auth.uid() is not null and public.my_role() is not null);
create policy calendars_update on public.calendars for update to authenticated using (auth.uid() is not null and public.my_role() is not null) with check (auth.uid() is not null and public.my_role() is not null);
create policy calendars_delete on public.calendars for delete to authenticated using (public.has_role(array['owner', 'admin', 'manager']));

alter table public.events enable row level security;
revoke all on public.events from anon;
grant select, insert, update, delete on public.events to authenticated;
drop policy if exists events_select on public.events;
drop policy if exists events_insert on public.events;
drop policy if exists events_update on public.events;
drop policy if exists events_delete on public.events;
create policy events_select on public.events for select to authenticated using ((auth.uid() is not null and public.my_role() is not null) and (coalesce(visibility,'company') <> 'private' or created_by = auth.uid()::text or attendees ? auth.uid()::text));
create policy events_insert on public.events for insert to authenticated with check (auth.uid() is not null and public.my_role() is not null);
create policy events_update on public.events for update to authenticated using (auth.uid() is not null and public.my_role() is not null or created_by = auth.uid()::text) with check (auth.uid() is not null and public.my_role() is not null or created_by = auth.uid()::text);
create policy events_delete on public.events for delete to authenticated using (auth.uid() is not null and public.my_role() is not null);

alter table public.holidays enable row level security;
revoke all on public.holidays from anon;
grant select, insert, update, delete on public.holidays to authenticated;
drop policy if exists holidays_select on public.holidays;
drop policy if exists holidays_insert on public.holidays;
drop policy if exists holidays_update on public.holidays;
drop policy if exists holidays_delete on public.holidays;
create policy holidays_select on public.holidays for select to authenticated using (auth.uid() is not null and public.my_role() is not null);
create policy holidays_insert on public.holidays for insert to authenticated with check (public.has_role(array['owner', 'admin', 'manager']));
create policy holidays_update on public.holidays for update to authenticated using (public.has_role(array['owner', 'admin', 'manager'])) with check (public.has_role(array['owner', 'admin', 'manager']));
create policy holidays_delete on public.holidays for delete to authenticated using (public.has_role(array['owner', 'admin', 'manager']));

alter table public.tasks enable row level security;
revoke all on public.tasks from anon;
grant select, insert, update, delete on public.tasks to authenticated;
drop policy if exists tasks_select on public.tasks;
drop policy if exists tasks_insert on public.tasks;
drop policy if exists tasks_update on public.tasks;
drop policy if exists tasks_delete on public.tasks;
create policy tasks_select on public.tasks for select to authenticated using (auth.uid() is not null and public.my_role() is not null);
create policy tasks_insert on public.tasks for insert to authenticated with check (auth.uid() is not null and public.my_role() is not null);
create policy tasks_update on public.tasks for update to authenticated using (auth.uid() is not null and public.my_role() is not null or created_by = auth.uid()::text) with check (auth.uid() is not null and public.my_role() is not null or created_by = auth.uid()::text);
create policy tasks_delete on public.tasks for delete to authenticated using (auth.uid() is not null and public.my_role() is not null);

alter table public.notes enable row level security;
revoke all on public.notes from anon;
grant select, insert, update, delete on public.notes to authenticated;
drop policy if exists notes_select on public.notes;
drop policy if exists notes_insert on public.notes;
drop policy if exists notes_update on public.notes;
drop policy if exists notes_delete on public.notes;
create policy notes_select on public.notes for select to authenticated using ((auth.uid() is not null and public.my_role() is not null) and (coalesce(shared, true) or created_by = auth.uid()::text));
create policy notes_insert on public.notes for insert to authenticated with check (auth.uid() is not null and public.my_role() is not null);
create policy notes_update on public.notes for update to authenticated using (auth.uid() is not null and public.my_role() is not null or created_by = auth.uid()::text) with check (auth.uid() is not null and public.my_role() is not null or created_by = auth.uid()::text);
create policy notes_delete on public.notes for delete to authenticated using (auth.uid() is not null and public.my_role() is not null);

alter table public.contacts enable row level security;
revoke all on public.contacts from anon;
grant select, insert, update, delete on public.contacts to authenticated;
drop policy if exists contacts_select on public.contacts;
drop policy if exists contacts_insert on public.contacts;
drop policy if exists contacts_update on public.contacts;
drop policy if exists contacts_delete on public.contacts;
create policy contacts_select on public.contacts for select to authenticated using (auth.uid() is not null and public.my_role() is not null);
create policy contacts_insert on public.contacts for insert to authenticated with check (auth.uid() is not null and public.my_role() is not null);
create policy contacts_update on public.contacts for update to authenticated using (auth.uid() is not null and public.my_role() is not null) with check (auth.uid() is not null and public.my_role() is not null);
create policy contacts_delete on public.contacts for delete to authenticated using (public.has_role(array['owner', 'admin', 'manager']));

alter table public.notifications enable row level security;
revoke all on public.notifications from anon;
grant select, insert, update, delete on public.notifications to authenticated;
drop policy if exists notifications_select on public.notifications;
drop policy if exists notifications_insert on public.notifications;
drop policy if exists notifications_update on public.notifications;
drop policy if exists notifications_delete on public.notifications;
create policy notifications_select on public.notifications for select to authenticated using (user_id = auth.uid()::text or public.has_role(array[]::text[]));
create policy notifications_insert on public.notifications for insert to authenticated with check (auth.uid() is not null);
create policy notifications_update on public.notifications for update to authenticated using (user_id = auth.uid()::text) with check (user_id = auth.uid()::text);
create policy notifications_delete on public.notifications for delete to authenticated using (user_id = auth.uid()::text or public.has_role(array[]::text[]));

alter table public.mail_messages enable row level security;
revoke all on public.mail_messages from anon;
grant select, insert, update, delete on public.mail_messages to authenticated;
drop policy if exists mail_messages_select on public.mail_messages;
drop policy if exists mail_messages_insert on public.mail_messages;
drop policy if exists mail_messages_update on public.mail_messages;
drop policy if exists mail_messages_delete on public.mail_messages;
create policy mail_messages_select on public.mail_messages for select to authenticated using ((auth.uid() is not null and public.my_role() is not null) and (from_user_id = auth.uid()::text or "to"::text like '%' || auth.uid()::text || '%' or cc::text like '%' || auth.uid()::text || '%' or bcc::text like '%' || auth.uid()::text || '%' or public.has_role(array[]::text[])));
create policy mail_messages_insert on public.mail_messages for insert to authenticated with check (auth.uid() is not null and public.my_role() is not null);
create policy mail_messages_update on public.mail_messages for update to authenticated using (auth.uid() is not null and public.my_role() is not null or created_by = auth.uid()::text) with check (auth.uid() is not null and public.my_role() is not null or created_by = auth.uid()::text);
create policy mail_messages_delete on public.mail_messages for delete to authenticated using (auth.uid() is not null and public.my_role() is not null);

alter table public.mail_flags enable row level security;
revoke all on public.mail_flags from anon;
grant select, insert, update, delete on public.mail_flags to authenticated;
drop policy if exists mail_flags_select on public.mail_flags;
drop policy if exists mail_flags_insert on public.mail_flags;
drop policy if exists mail_flags_update on public.mail_flags;
drop policy if exists mail_flags_delete on public.mail_flags;
create policy mail_flags_select on public.mail_flags for select to authenticated using (user_id = auth.uid()::text or public.has_role(array[]::text[]));
create policy mail_flags_insert on public.mail_flags for insert to authenticated with check (auth.uid() is not null);
create policy mail_flags_update on public.mail_flags for update to authenticated using (user_id = auth.uid()::text) with check (user_id = auth.uid()::text);
create policy mail_flags_delete on public.mail_flags for delete to authenticated using (user_id = auth.uid()::text or public.has_role(array[]::text[]));

alter table public.mail_templates enable row level security;
revoke all on public.mail_templates from anon;
grant select, insert, update, delete on public.mail_templates to authenticated;
drop policy if exists mail_templates_select on public.mail_templates;
drop policy if exists mail_templates_insert on public.mail_templates;
drop policy if exists mail_templates_update on public.mail_templates;
drop policy if exists mail_templates_delete on public.mail_templates;
create policy mail_templates_select on public.mail_templates for select to authenticated using (auth.uid() is not null and public.my_role() is not null);
create policy mail_templates_insert on public.mail_templates for insert to authenticated with check (public.has_role(array['owner', 'admin', 'manager', 'sales', 'finance']));
create policy mail_templates_update on public.mail_templates for update to authenticated using (public.has_role(array['owner', 'admin', 'manager', 'sales', 'finance'])) with check (public.has_role(array['owner', 'admin', 'manager', 'sales', 'finance']));
create policy mail_templates_delete on public.mail_templates for delete to authenticated using (public.has_role(array['owner', 'admin', 'manager']));

alter table public.chat_channels enable row level security;
revoke all on public.chat_channels from anon;
grant select, insert, update, delete on public.chat_channels to authenticated;
drop policy if exists chat_channels_select on public.chat_channels;
drop policy if exists chat_channels_insert on public.chat_channels;
drop policy if exists chat_channels_update on public.chat_channels;
drop policy if exists chat_channels_delete on public.chat_channels;
create policy chat_channels_select on public.chat_channels for select to authenticated using ((auth.uid() is not null and public.my_role() is not null) and (not coalesce(private,false) or members ? auth.uid()::text or created_by = auth.uid()::text));
create policy chat_channels_insert on public.chat_channels for insert to authenticated with check (auth.uid() is not null and public.my_role() is not null);
create policy chat_channels_update on public.chat_channels for update to authenticated using (auth.uid() is not null and public.my_role() is not null) with check (auth.uid() is not null and public.my_role() is not null);
create policy chat_channels_delete on public.chat_channels for delete to authenticated using (public.has_role(array['owner', 'admin', 'manager']));

alter table public.chat_messages enable row level security;
revoke all on public.chat_messages from anon;
grant select, insert, update, delete on public.chat_messages to authenticated;
drop policy if exists chat_messages_select on public.chat_messages;
drop policy if exists chat_messages_insert on public.chat_messages;
drop policy if exists chat_messages_update on public.chat_messages;
drop policy if exists chat_messages_delete on public.chat_messages;
create policy chat_messages_select on public.chat_messages for select to authenticated using ((auth.uid() is not null and public.my_role() is not null) and exists (select 1 from public.chat_channels c where c.id = channel_id and (not coalesce(c.private,false) or c.members ? auth.uid()::text or c.created_by = auth.uid()::text)));
create policy chat_messages_insert on public.chat_messages for insert to authenticated with check (auth.uid() is not null and public.my_role() is not null);
create policy chat_messages_update on public.chat_messages for update to authenticated using (auth.uid() is not null and public.my_role() is not null or created_by = auth.uid()::text) with check (auth.uid() is not null and public.my_role() is not null or created_by = auth.uid()::text);
create policy chat_messages_delete on public.chat_messages for delete to authenticated using (auth.uid() is not null and public.my_role() is not null);

alter table public.chat_reads enable row level security;
revoke all on public.chat_reads from anon;
grant select, insert, update, delete on public.chat_reads to authenticated;
drop policy if exists chat_reads_select on public.chat_reads;
drop policy if exists chat_reads_insert on public.chat_reads;
drop policy if exists chat_reads_update on public.chat_reads;
drop policy if exists chat_reads_delete on public.chat_reads;
create policy chat_reads_select on public.chat_reads for select to authenticated using (user_id = auth.uid()::text or public.has_role(array[]::text[]));
create policy chat_reads_insert on public.chat_reads for insert to authenticated with check (auth.uid() is not null);
create policy chat_reads_update on public.chat_reads for update to authenticated using (user_id = auth.uid()::text) with check (user_id = auth.uid()::text);
create policy chat_reads_delete on public.chat_reads for delete to authenticated using (user_id = auth.uid()::text or public.has_role(array[]::text[]));

alter table public.drives enable row level security;
revoke all on public.drives from anon;
grant select, insert, update, delete on public.drives to authenticated;
drop policy if exists drives_select on public.drives;
drop policy if exists drives_insert on public.drives;
drop policy if exists drives_update on public.drives;
drop policy if exists drives_delete on public.drives;
create policy drives_select on public.drives for select to authenticated using (auth.uid() is not null and public.my_role() is not null);
create policy drives_insert on public.drives for insert to authenticated with check (public.has_role(array['owner', 'admin']));
create policy drives_update on public.drives for update to authenticated using (public.has_role(array['owner', 'admin'])) with check (public.has_role(array['owner', 'admin']));
create policy drives_delete on public.drives for delete to authenticated using (public.has_role(array['owner']));

alter table public.folders enable row level security;
revoke all on public.folders from anon;
grant select, insert, update, delete on public.folders to authenticated;
drop policy if exists folders_select on public.folders;
drop policy if exists folders_insert on public.folders;
drop policy if exists folders_update on public.folders;
drop policy if exists folders_delete on public.folders;
create policy folders_select on public.folders for select to authenticated using ((auth.uid() is not null and public.my_role() is not null) and public.can_see_drive(drive_id));
create policy folders_insert on public.folders for insert to authenticated with check ((auth.uid() is not null and public.my_role() is not null) and public.can_see_drive(drive_id));
create policy folders_update on public.folders for update to authenticated using ((auth.uid() is not null and public.my_role() is not null or created_by = auth.uid()::text) and public.can_see_drive(drive_id)) with check ((auth.uid() is not null and public.my_role() is not null or created_by = auth.uid()::text) and public.can_see_drive(drive_id));
create policy folders_delete on public.folders for delete to authenticated using ((public.has_role(array['owner', 'admin', 'manager'])) and public.can_see_drive(drive_id));

alter table public.files enable row level security;
revoke all on public.files from anon;
grant select, insert, update, delete on public.files to authenticated;
drop policy if exists files_select on public.files;
drop policy if exists files_insert on public.files;
drop policy if exists files_update on public.files;
drop policy if exists files_delete on public.files;
create policy files_select on public.files for select to authenticated using ((auth.uid() is not null and public.my_role() is not null) and ((not coalesce(confidential,false) or public.has_role(array['manager','hr']) or created_by = auth.uid()::text) and public.can_see_drive(drive_id)));
create policy files_insert on public.files for insert to authenticated with check ((auth.uid() is not null and public.my_role() is not null) and ((not coalesce(confidential,false) or public.has_role(array['manager','hr']) or created_by = auth.uid()::text) and public.can_see_drive(drive_id)));
create policy files_update on public.files for update to authenticated using ((auth.uid() is not null and public.my_role() is not null or created_by = auth.uid()::text) and ((not coalesce(confidential,false) or public.has_role(array['manager','hr']) or created_by = auth.uid()::text) and public.can_see_drive(drive_id))) with check ((auth.uid() is not null and public.my_role() is not null or created_by = auth.uid()::text) and ((not coalesce(confidential,false) or public.has_role(array['manager','hr']) or created_by = auth.uid()::text) and public.can_see_drive(drive_id)));
create policy files_delete on public.files for delete to authenticated using ((public.has_role(array['owner', 'admin', 'manager'])) and ((not coalesce(confidential,false) or public.has_role(array['manager','hr']) or created_by = auth.uid()::text) and public.can_see_drive(drive_id)));

alter table public.docs enable row level security;
revoke all on public.docs from anon;
grant select, insert, update, delete on public.docs to authenticated;
drop policy if exists docs_select on public.docs;
drop policy if exists docs_insert on public.docs;
drop policy if exists docs_update on public.docs;
drop policy if exists docs_delete on public.docs;
create policy docs_select on public.docs for select to authenticated using (auth.uid() is not null and public.my_role() is not null);
create policy docs_insert on public.docs for insert to authenticated with check (auth.uid() is not null and public.my_role() is not null);
create policy docs_update on public.docs for update to authenticated using (auth.uid() is not null and public.my_role() is not null or created_by = auth.uid()::text) with check (auth.uid() is not null and public.my_role() is not null or created_by = auth.uid()::text);
create policy docs_delete on public.docs for delete to authenticated using (auth.uid() is not null and public.my_role() is not null);

alter table public.sheets enable row level security;
revoke all on public.sheets from anon;
grant select, insert, update, delete on public.sheets to authenticated;
drop policy if exists sheets_select on public.sheets;
drop policy if exists sheets_insert on public.sheets;
drop policy if exists sheets_update on public.sheets;
drop policy if exists sheets_delete on public.sheets;
create policy sheets_select on public.sheets for select to authenticated using ((auth.uid() is not null and public.my_role() is not null) and (restricted_to is null or jsonb_typeof(restricted_to) <> 'array' or jsonb_array_length(restricted_to) = 0 or created_by = auth.uid()::text or public.my_role() in (select jsonb_array_elements_text(restricted_to)) or public.has_role(array[]::text[])));
create policy sheets_insert on public.sheets for insert to authenticated with check ((auth.uid() is not null and public.my_role() is not null) and (restricted_to is null or jsonb_typeof(restricted_to) <> 'array' or jsonb_array_length(restricted_to) = 0 or created_by = auth.uid()::text or public.my_role() in (select jsonb_array_elements_text(restricted_to)) or public.has_role(array[]::text[])));
create policy sheets_update on public.sheets for update to authenticated using ((auth.uid() is not null and public.my_role() is not null or created_by = auth.uid()::text) and (restricted_to is null or jsonb_typeof(restricted_to) <> 'array' or jsonb_array_length(restricted_to) = 0 or created_by = auth.uid()::text or public.my_role() in (select jsonb_array_elements_text(restricted_to)) or public.has_role(array[]::text[]))) with check ((auth.uid() is not null and public.my_role() is not null or created_by = auth.uid()::text) and (restricted_to is null or jsonb_typeof(restricted_to) <> 'array' or jsonb_array_length(restricted_to) = 0 or created_by = auth.uid()::text or public.my_role() in (select jsonb_array_elements_text(restricted_to)) or public.has_role(array[]::text[])));
create policy sheets_delete on public.sheets for delete to authenticated using ((auth.uid() is not null and public.my_role() is not null) and (restricted_to is null or jsonb_typeof(restricted_to) <> 'array' or jsonb_array_length(restricted_to) = 0 or created_by = auth.uid()::text or public.my_role() in (select jsonb_array_elements_text(restricted_to)) or public.has_role(array[]::text[])));

alter table public.slides enable row level security;
revoke all on public.slides from anon;
grant select, insert, update, delete on public.slides to authenticated;
drop policy if exists slides_select on public.slides;
drop policy if exists slides_insert on public.slides;
drop policy if exists slides_update on public.slides;
drop policy if exists slides_delete on public.slides;
create policy slides_select on public.slides for select to authenticated using (auth.uid() is not null and public.my_role() is not null);
create policy slides_insert on public.slides for insert to authenticated with check (auth.uid() is not null and public.my_role() is not null);
create policy slides_update on public.slides for update to authenticated using (auth.uid() is not null and public.my_role() is not null or created_by = auth.uid()::text) with check (auth.uid() is not null and public.my_role() is not null or created_by = auth.uid()::text);
create policy slides_delete on public.slides for delete to authenticated using (auth.uid() is not null and public.my_role() is not null);

alter table public.forms enable row level security;
revoke all on public.forms from anon;
grant select, insert, update, delete on public.forms to authenticated;
drop policy if exists forms_select on public.forms;
drop policy if exists forms_insert on public.forms;
drop policy if exists forms_update on public.forms;
drop policy if exists forms_delete on public.forms;
create policy forms_select on public.forms for select to authenticated using (auth.uid() is not null and public.my_role() is not null);
create policy forms_insert on public.forms for insert to authenticated with check (public.has_role(array['owner', 'admin', 'manager', 'hr', 'operations']));
create policy forms_update on public.forms for update to authenticated using (public.has_role(array['owner', 'admin', 'manager', 'hr', 'operations'])) with check (public.has_role(array['owner', 'admin', 'manager', 'hr', 'operations']));
create policy forms_delete on public.forms for delete to authenticated using (public.has_role(array['owner', 'admin', 'manager']));

alter table public.form_responses enable row level security;
revoke all on public.form_responses from anon;
grant select, insert, update, delete on public.form_responses to authenticated;
drop policy if exists form_responses_select on public.form_responses;
drop policy if exists form_responses_insert on public.form_responses;
drop policy if exists form_responses_update on public.form_responses;
drop policy if exists form_responses_delete on public.form_responses;
create policy form_responses_select on public.form_responses for select to authenticated using ((auth.uid() is not null and public.my_role() is not null) and (coalesce(form_category, '') not in ('hr', 'incident') or created_by = auth.uid()::text or (form_category = 'hr' and public.has_role(array['manager','hr'])) or (form_category = 'incident' and public.has_role(array['manager','hr','operations']))));
create policy form_responses_insert on public.form_responses for insert to authenticated with check ((auth.uid() is not null and public.my_role() is not null) and (coalesce(form_category, '') not in ('hr', 'incident') or created_by = auth.uid()::text or (form_category = 'hr' and public.has_role(array['manager','hr'])) or (form_category = 'incident' and public.has_role(array['manager','hr','operations']))));
create policy form_responses_update on public.form_responses for update to authenticated using ((public.has_role(array['owner', 'admin', 'manager', 'hr', 'operations'])) and (coalesce(form_category, '') not in ('hr', 'incident') or created_by = auth.uid()::text or (form_category = 'hr' and public.has_role(array['manager','hr'])) or (form_category = 'incident' and public.has_role(array['manager','hr','operations'])))) with check ((public.has_role(array['owner', 'admin', 'manager', 'hr', 'operations'])) and (coalesce(form_category, '') not in ('hr', 'incident') or created_by = auth.uid()::text or (form_category = 'hr' and public.has_role(array['manager','hr'])) or (form_category = 'incident' and public.has_role(array['manager','hr','operations']))));
create policy form_responses_delete on public.form_responses for delete to authenticated using ((public.has_role(array['owner', 'admin', 'manager'])) and (coalesce(form_category, '') not in ('hr', 'incident') or created_by = auth.uid()::text or (form_category = 'hr' and public.has_role(array['manager','hr'])) or (form_category = 'incident' and public.has_role(array['manager','hr','operations']))));

alter table public.comments enable row level security;
revoke all on public.comments from anon;
grant select, insert, update, delete on public.comments to authenticated;
drop policy if exists comments_select on public.comments;
drop policy if exists comments_insert on public.comments;
drop policy if exists comments_update on public.comments;
drop policy if exists comments_delete on public.comments;
create policy comments_select on public.comments for select to authenticated using (auth.uid() is not null and public.my_role() is not null);
create policy comments_insert on public.comments for insert to authenticated with check (auth.uid() is not null and public.my_role() is not null);
create policy comments_update on public.comments for update to authenticated using (auth.uid() is not null and public.my_role() is not null or created_by = auth.uid()::text) with check (auth.uid() is not null and public.my_role() is not null or created_by = auth.uid()::text);
create policy comments_delete on public.comments for delete to authenticated using (auth.uid() is not null and public.my_role() is not null);

alter table public.audit_log enable row level security;
revoke all on public.audit_log from anon;
grant select, insert, update, delete on public.audit_log to authenticated;
drop policy if exists audit_log_select on public.audit_log;
drop policy if exists audit_log_insert on public.audit_log;
drop policy if exists audit_log_update on public.audit_log;
drop policy if exists audit_log_delete on public.audit_log;
create policy audit_log_select on public.audit_log for select to authenticated using (public.has_role(array['owner', 'admin', 'manager']));
create policy audit_log_insert on public.audit_log for insert to authenticated with check (public.has_role(array[]::text[]));
create policy audit_log_update on public.audit_log for update to authenticated using (public.has_role(array[]::text[])) with check (public.has_role(array[]::text[]));
create policy audit_log_delete on public.audit_log for delete to authenticated using (public.has_role(array[]::text[]));

alter table public.ml_models enable row level security;
revoke all on public.ml_models from anon;
grant select, insert, update, delete on public.ml_models to authenticated;
drop policy if exists ml_models_select on public.ml_models;
drop policy if exists ml_models_insert on public.ml_models;
drop policy if exists ml_models_update on public.ml_models;
drop policy if exists ml_models_delete on public.ml_models;
create policy ml_models_select on public.ml_models for select to authenticated using (auth.uid() is not null and public.my_role() is not null);
create policy ml_models_insert on public.ml_models for insert to authenticated with check (auth.uid() is not null and public.my_role() is not null);
create policy ml_models_update on public.ml_models for update to authenticated using (auth.uid() is not null and public.my_role() is not null) with check (auth.uid() is not null and public.my_role() is not null);
create policy ml_models_delete on public.ml_models for delete to authenticated using (public.has_role(array['owner', 'admin', 'manager']));

alter table public.predictions enable row level security;
revoke all on public.predictions from anon;
grant select, insert, update, delete on public.predictions to authenticated;
drop policy if exists predictions_select on public.predictions;
drop policy if exists predictions_insert on public.predictions;
drop policy if exists predictions_update on public.predictions;
drop policy if exists predictions_delete on public.predictions;
create policy predictions_select on public.predictions for select to authenticated using (auth.uid() is not null and public.my_role() is not null);
create policy predictions_insert on public.predictions for insert to authenticated with check (auth.uid() is not null and public.my_role() is not null);
create policy predictions_update on public.predictions for update to authenticated using (auth.uid() is not null and public.my_role() is not null) with check (auth.uid() is not null and public.my_role() is not null);
create policy predictions_delete on public.predictions for delete to authenticated using (public.has_role(array['owner', 'admin', 'manager']));

alter table public.ai_conversations enable row level security;
revoke all on public.ai_conversations from anon;
grant select, insert, update, delete on public.ai_conversations to authenticated;
drop policy if exists ai_conversations_select on public.ai_conversations;
drop policy if exists ai_conversations_insert on public.ai_conversations;
drop policy if exists ai_conversations_update on public.ai_conversations;
drop policy if exists ai_conversations_delete on public.ai_conversations;
create policy ai_conversations_select on public.ai_conversations for select to authenticated using (user_id = auth.uid()::text or public.has_role(array[]::text[]));
create policy ai_conversations_insert on public.ai_conversations for insert to authenticated with check (auth.uid() is not null);
create policy ai_conversations_update on public.ai_conversations for update to authenticated using (user_id = auth.uid()::text) with check (user_id = auth.uid()::text);
create policy ai_conversations_delete on public.ai_conversations for delete to authenticated using (user_id = auth.uid()::text or public.has_role(array[]::text[]));

alter table public.clients enable row level security;
revoke all on public.clients from anon;
grant select, insert, update, delete on public.clients to authenticated;
drop policy if exists clients_select on public.clients;
drop policy if exists clients_insert on public.clients;
drop policy if exists clients_update on public.clients;
drop policy if exists clients_delete on public.clients;
create policy clients_select on public.clients for select to authenticated using (auth.uid() is not null and public.my_role() is not null);
create policy clients_insert on public.clients for insert to authenticated with check (public.has_role(array['manager', 'sales', 'operations', 'finance', 'supervisor']));
create policy clients_update on public.clients for update to authenticated using (public.has_role(array['manager', 'sales', 'operations', 'finance', 'supervisor'])) with check (public.has_role(array['manager', 'sales', 'operations', 'finance', 'supervisor']));
create policy clients_delete on public.clients for delete to authenticated using (public.has_role(array['manager']));

alter table public.sites enable row level security;
revoke all on public.sites from anon;
grant select, insert, update, delete on public.sites to authenticated;
drop policy if exists sites_select on public.sites;
drop policy if exists sites_insert on public.sites;
drop policy if exists sites_update on public.sites;
drop policy if exists sites_delete on public.sites;
create policy sites_select on public.sites for select to authenticated using (auth.uid() is not null and public.my_role() is not null);
create policy sites_insert on public.sites for insert to authenticated with check (public.has_role(array['manager', 'sales', 'operations', 'supervisor']));
create policy sites_update on public.sites for update to authenticated using (public.has_role(array['manager', 'sales', 'operations', 'supervisor'])) with check (public.has_role(array['manager', 'sales', 'operations', 'supervisor']));
create policy sites_delete on public.sites for delete to authenticated using (public.has_role(array['manager']));

alter table public.contracts enable row level security;
revoke all on public.contracts from anon;
grant select, insert, update, delete on public.contracts to authenticated;
drop policy if exists contracts_select on public.contracts;
drop policy if exists contracts_insert on public.contracts;
drop policy if exists contracts_update on public.contracts;
drop policy if exists contracts_delete on public.contracts;
create policy contracts_select on public.contracts for select to authenticated using (auth.uid() is not null and public.my_role() is not null);
create policy contracts_insert on public.contracts for insert to authenticated with check (public.has_role(array['manager', 'sales', 'finance', 'operations']));
create policy contracts_update on public.contracts for update to authenticated using (public.has_role(array['manager', 'sales', 'finance', 'operations'])) with check (public.has_role(array['manager', 'sales', 'finance', 'operations']));
create policy contracts_delete on public.contracts for delete to authenticated using (public.has_role(array['manager']));
-- Sensitive columns (monthly_value, per_visit_rate) are only returned to owner, admin, manager, finance, sales, operations: they are left out of the
-- column grant below and served by the view public.contracts_sensitive (row filter on the role).
revoke select on public.contracts from authenticated;
grant select (id, created_at, created_by, created_by_name, updated_at, updated_by, updated_by_name, deleted_at, deleted_by, deleted_by_name, _src, _seed, data, client_id, site_id, legacy_code, name, site_name, service_type, frequency, visits_per_month, status, start_date, end_date, pause_from, pause_until, pause_reason, preferred_days, preferred_time, crew_id, billing_status, annual_increase_month, salesperson, notes) on public.contracts to authenticated;
create or replace view public.contracts_sensitive with (security_barrier = true) as
  select id, monthly_value, per_visit_rate from public.contracts where public.has_role(array['manager', 'finance', 'sales', 'operations']);
revoke all on public.contracts_sensitive from public, anon;
grant select on public.contracts_sensitive to authenticated;

alter table public.contract_changes enable row level security;
revoke all on public.contract_changes from anon;
grant select, insert, update, delete on public.contract_changes to authenticated;
drop policy if exists contract_changes_select on public.contract_changes;
drop policy if exists contract_changes_insert on public.contract_changes;
drop policy if exists contract_changes_update on public.contract_changes;
drop policy if exists contract_changes_delete on public.contract_changes;
create policy contract_changes_select on public.contract_changes for select to authenticated using (public.has_role(array['manager', 'finance', 'hr', 'sales', 'operations']));
create policy contract_changes_insert on public.contract_changes for insert to authenticated with check (public.has_role(array['manager', 'sales', 'finance']));
create policy contract_changes_update on public.contract_changes for update to authenticated using (public.has_role(array['manager', 'sales', 'finance'])) with check (public.has_role(array['manager', 'sales', 'finance']));
create policy contract_changes_delete on public.contract_changes for delete to authenticated using (public.has_role(array['manager']));

alter table public.leads enable row level security;
revoke all on public.leads from anon;
grant select, insert, update, delete on public.leads to authenticated;
drop policy if exists leads_select on public.leads;
drop policy if exists leads_insert on public.leads;
drop policy if exists leads_update on public.leads;
drop policy if exists leads_delete on public.leads;
create policy leads_select on public.leads for select to authenticated using (public.has_role(array['manager', 'sales', 'finance']));
create policy leads_insert on public.leads for insert to authenticated with check (public.has_role(array['manager', 'sales']));
create policy leads_update on public.leads for update to authenticated using (public.has_role(array['manager', 'sales'])) with check (public.has_role(array['manager', 'sales']));
create policy leads_delete on public.leads for delete to authenticated using (public.has_role(array['manager']));

alter table public.prospects enable row level security;
revoke all on public.prospects from anon;
grant select, insert, update, delete on public.prospects to authenticated;
drop policy if exists prospects_select on public.prospects;
drop policy if exists prospects_insert on public.prospects;
drop policy if exists prospects_update on public.prospects;
drop policy if exists prospects_delete on public.prospects;
create policy prospects_select on public.prospects for select to authenticated using (public.has_role(array['manager', 'sales']));
create policy prospects_insert on public.prospects for insert to authenticated with check (public.has_role(array['manager', 'sales']));
create policy prospects_update on public.prospects for update to authenticated using (public.has_role(array['manager', 'sales'])) with check (public.has_role(array['manager', 'sales']));
create policy prospects_delete on public.prospects for delete to authenticated using (public.has_role(array['manager']));

alter table public.call_attempts enable row level security;
revoke all on public.call_attempts from anon;
grant select, insert, update, delete on public.call_attempts to authenticated;
drop policy if exists call_attempts_select on public.call_attempts;
drop policy if exists call_attempts_insert on public.call_attempts;
drop policy if exists call_attempts_update on public.call_attempts;
drop policy if exists call_attempts_delete on public.call_attempts;
create policy call_attempts_select on public.call_attempts for select to authenticated using (public.has_role(array['manager', 'sales']));
create policy call_attempts_insert on public.call_attempts for insert to authenticated with check (public.has_role(array['manager', 'sales']));
create policy call_attempts_update on public.call_attempts for update to authenticated using (public.has_role(array['manager', 'sales'])) with check (public.has_role(array['manager', 'sales']));
create policy call_attempts_delete on public.call_attempts for delete to authenticated using (public.has_role(array['manager']));

alter table public.services enable row level security;
revoke all on public.services from anon;
grant select, insert, update, delete on public.services to authenticated;
drop policy if exists services_select on public.services;
drop policy if exists services_insert on public.services;
drop policy if exists services_update on public.services;
drop policy if exists services_delete on public.services;
create policy services_select on public.services for select to authenticated using (auth.uid() is not null and public.my_role() is not null);
create policy services_insert on public.services for insert to authenticated with check (public.has_role(array['manager', 'sales', 'finance']));
create policy services_update on public.services for update to authenticated using (public.has_role(array['manager', 'sales', 'finance'])) with check (public.has_role(array['manager', 'sales', 'finance']));
create policy services_delete on public.services for delete to authenticated using (public.has_role(array['manager']));

alter table public.quotes enable row level security;
revoke all on public.quotes from anon;
grant select, insert, update, delete on public.quotes to authenticated;
drop policy if exists quotes_select on public.quotes;
drop policy if exists quotes_insert on public.quotes;
drop policy if exists quotes_update on public.quotes;
drop policy if exists quotes_delete on public.quotes;
create policy quotes_select on public.quotes for select to authenticated using (public.has_role(array['manager', 'sales', 'finance', 'operations']));
create policy quotes_insert on public.quotes for insert to authenticated with check (public.has_role(array['manager', 'sales', 'finance']));
create policy quotes_update on public.quotes for update to authenticated using (public.has_role(array['manager', 'sales', 'finance'])) with check (public.has_role(array['manager', 'sales', 'finance']));
create policy quotes_delete on public.quotes for delete to authenticated using (public.has_role(array['manager']));

alter table public.invoices enable row level security;
revoke all on public.invoices from anon;
grant select, insert, update, delete on public.invoices to authenticated;
drop policy if exists invoices_select on public.invoices;
drop policy if exists invoices_insert on public.invoices;
drop policy if exists invoices_update on public.invoices;
drop policy if exists invoices_delete on public.invoices;
create policy invoices_select on public.invoices for select to authenticated using (public.has_role(array['manager', 'finance', 'sales', 'supervisor']));
create policy invoices_insert on public.invoices for insert to authenticated with check (public.has_role(array['manager', 'finance', 'sales', 'supervisor']));
create policy invoices_update on public.invoices for update to authenticated using (public.has_role(array['manager', 'finance', 'sales', 'supervisor'])) with check (public.has_role(array['manager', 'finance', 'sales', 'supervisor']));
create policy invoices_delete on public.invoices for delete to authenticated using (public.has_role(array['manager', 'finance']));

alter table public.payments enable row level security;
revoke all on public.payments from anon;
grant select, insert, update, delete on public.payments to authenticated;
drop policy if exists payments_select on public.payments;
drop policy if exists payments_insert on public.payments;
drop policy if exists payments_update on public.payments;
drop policy if exists payments_delete on public.payments;
create policy payments_select on public.payments for select to authenticated using (public.has_role(array['manager', 'finance']));
create policy payments_insert on public.payments for insert to authenticated with check (public.has_role(array['manager', 'finance', 'sales']));
create policy payments_update on public.payments for update to authenticated using (public.has_role(array['manager', 'finance', 'sales'])) with check (public.has_role(array['manager', 'finance', 'sales']));
create policy payments_delete on public.payments for delete to authenticated using (public.has_role(array['manager', 'finance']));

alter table public.crews enable row level security;
revoke all on public.crews from anon;
grant select, insert, update, delete on public.crews to authenticated;
drop policy if exists crews_select on public.crews;
drop policy if exists crews_insert on public.crews;
drop policy if exists crews_update on public.crews;
drop policy if exists crews_delete on public.crews;
create policy crews_select on public.crews for select to authenticated using (auth.uid() is not null and public.my_role() is not null);
create policy crews_insert on public.crews for insert to authenticated with check (public.has_role(array['manager', 'operations', 'supervisor']));
create policy crews_update on public.crews for update to authenticated using (public.has_role(array['manager', 'operations', 'supervisor'])) with check (public.has_role(array['manager', 'operations', 'supervisor']));
create policy crews_delete on public.crews for delete to authenticated using (public.has_role(array['manager']));

alter table public.visits enable row level security;
revoke all on public.visits from anon;
grant select, insert, update, delete on public.visits to authenticated;
drop policy if exists visits_select on public.visits;
drop policy if exists visits_insert on public.visits;
drop policy if exists visits_update on public.visits;
drop policy if exists visits_delete on public.visits;
create policy visits_select on public.visits for select to authenticated using (auth.uid() is not null and public.my_role() is not null);
create policy visits_insert on public.visits for insert to authenticated with check (auth.uid() is not null and public.my_role() is not null);
create policy visits_update on public.visits for update to authenticated using (auth.uid() is not null and public.my_role() is not null) with check (auth.uid() is not null and public.my_role() is not null);
create policy visits_delete on public.visits for delete to authenticated using (public.has_role(array['manager', 'operations', 'supervisor']));

alter table public.jobs enable row level security;
revoke all on public.jobs from anon;
grant select, insert, update, delete on public.jobs to authenticated;
drop policy if exists jobs_select on public.jobs;
drop policy if exists jobs_insert on public.jobs;
drop policy if exists jobs_update on public.jobs;
drop policy if exists jobs_delete on public.jobs;
create policy jobs_select on public.jobs for select to authenticated using (auth.uid() is not null and public.my_role() is not null);
create policy jobs_insert on public.jobs for insert to authenticated with check (public.has_role(array['manager', 'operations', 'sales', 'supervisor', 'finance']));
create policy jobs_update on public.jobs for update to authenticated using (public.has_role(array['manager', 'operations', 'sales', 'supervisor', 'finance'])) with check (public.has_role(array['manager', 'operations', 'sales', 'supervisor', 'finance']));
create policy jobs_delete on public.jobs for delete to authenticated using (public.has_role(array['manager']));
-- Sensitive columns (value, deposit, cost, profit, owing) are only returned to owner, admin, manager, finance, sales, operations: they are left out of the
-- column grant below and served by the view public.jobs_sensitive (row filter on the role).
revoke select on public.jobs from authenticated;
grant select (id, created_at, created_by, created_by_name, updated_at, updated_by, updated_by_name, deleted_at, deleted_by, deleted_by_name, _src, _seed, data, number, title, client_id, client_name, site_address, suburb, service_type, quote_id, status, month, booked_date, start_date, est_finish, completed_date, deposit_status, est_hours, actual_hours, supervisor, team, vehicle_id, salesperson, invoice_status, notes) on public.jobs to authenticated;
create or replace view public.jobs_sensitive with (security_barrier = true) as
  select id, value, deposit, cost, profit, owing from public.jobs where public.has_role(array['manager', 'finance', 'sales', 'operations']);
revoke all on public.jobs_sensitive from public, anon;
grant select on public.jobs_sensitive to authenticated;

alter table public.job_costs enable row level security;
revoke all on public.job_costs from anon;
grant select, insert, update, delete on public.job_costs to authenticated;
drop policy if exists job_costs_select on public.job_costs;
drop policy if exists job_costs_insert on public.job_costs;
drop policy if exists job_costs_update on public.job_costs;
drop policy if exists job_costs_delete on public.job_costs;
create policy job_costs_select on public.job_costs for select to authenticated using (public.has_role(array['manager', 'finance', 'hr', 'sales', 'operations']));
create policy job_costs_insert on public.job_costs for insert to authenticated with check (public.has_role(array['manager', 'operations', 'finance']));
create policy job_costs_update on public.job_costs for update to authenticated using (public.has_role(array['manager', 'operations', 'finance'])) with check (public.has_role(array['manager', 'operations', 'finance']));
create policy job_costs_delete on public.job_costs for delete to authenticated using (public.has_role(array['manager', 'finance']));

alter table public.vehicles enable row level security;
revoke all on public.vehicles from anon;
grant select, insert, update, delete on public.vehicles to authenticated;
drop policy if exists vehicles_select on public.vehicles;
drop policy if exists vehicles_insert on public.vehicles;
drop policy if exists vehicles_update on public.vehicles;
drop policy if exists vehicles_delete on public.vehicles;
create policy vehicles_select on public.vehicles for select to authenticated using (auth.uid() is not null and public.my_role() is not null);
create policy vehicles_insert on public.vehicles for insert to authenticated with check (public.has_role(array['manager', 'operations', 'finance']));
create policy vehicles_update on public.vehicles for update to authenticated using (public.has_role(array['manager', 'operations', 'finance'])) with check (public.has_role(array['manager', 'operations', 'finance']));
create policy vehicles_delete on public.vehicles for delete to authenticated using (public.has_role(array['manager']));

alter table public.vehicle_logs enable row level security;
revoke all on public.vehicle_logs from anon;
grant select, insert, update, delete on public.vehicle_logs to authenticated;
drop policy if exists vehicle_logs_select on public.vehicle_logs;
drop policy if exists vehicle_logs_insert on public.vehicle_logs;
drop policy if exists vehicle_logs_update on public.vehicle_logs;
drop policy if exists vehicle_logs_delete on public.vehicle_logs;
create policy vehicle_logs_select on public.vehicle_logs for select to authenticated using (auth.uid() is not null and public.my_role() is not null);
create policy vehicle_logs_insert on public.vehicle_logs for insert to authenticated with check (public.has_role(array['manager', 'operations', 'supervisor', 'finance', 'field']));
create policy vehicle_logs_update on public.vehicle_logs for update to authenticated using (public.has_role(array['manager', 'operations', 'supervisor', 'finance', 'field'])) with check (public.has_role(array['manager', 'operations', 'supervisor', 'finance', 'field']));
create policy vehicle_logs_delete on public.vehicle_logs for delete to authenticated using (public.has_role(array['manager']));

alter table public.assets enable row level security;
revoke all on public.assets from anon;
grant select, insert, update, delete on public.assets to authenticated;
drop policy if exists assets_select on public.assets;
drop policy if exists assets_insert on public.assets;
drop policy if exists assets_update on public.assets;
drop policy if exists assets_delete on public.assets;
create policy assets_select on public.assets for select to authenticated using (auth.uid() is not null and public.my_role() is not null);
create policy assets_insert on public.assets for insert to authenticated with check (public.has_role(array['manager', 'operations', 'supervisor', 'finance']));
create policy assets_update on public.assets for update to authenticated using (public.has_role(array['manager', 'operations', 'supervisor', 'finance'])) with check (public.has_role(array['manager', 'operations', 'supervisor', 'finance']));
create policy assets_delete on public.assets for delete to authenticated using (public.has_role(array['manager']));

alter table public.asset_maintenance enable row level security;
revoke all on public.asset_maintenance from anon;
grant select, insert, update, delete on public.asset_maintenance to authenticated;
drop policy if exists asset_maintenance_select on public.asset_maintenance;
drop policy if exists asset_maintenance_insert on public.asset_maintenance;
drop policy if exists asset_maintenance_update on public.asset_maintenance;
drop policy if exists asset_maintenance_delete on public.asset_maintenance;
create policy asset_maintenance_select on public.asset_maintenance for select to authenticated using (auth.uid() is not null and public.my_role() is not null);
create policy asset_maintenance_insert on public.asset_maintenance for insert to authenticated with check (public.has_role(array['manager', 'operations', 'supervisor']));
create policy asset_maintenance_update on public.asset_maintenance for update to authenticated using (public.has_role(array['manager', 'operations', 'supervisor'])) with check (public.has_role(array['manager', 'operations', 'supervisor']));
create policy asset_maintenance_delete on public.asset_maintenance for delete to authenticated using (public.has_role(array['manager']));

alter table public.suppliers enable row level security;
revoke all on public.suppliers from anon;
grant select, insert, update, delete on public.suppliers to authenticated;
drop policy if exists suppliers_select on public.suppliers;
drop policy if exists suppliers_insert on public.suppliers;
drop policy if exists suppliers_update on public.suppliers;
drop policy if exists suppliers_delete on public.suppliers;
create policy suppliers_select on public.suppliers for select to authenticated using (auth.uid() is not null and public.my_role() is not null);
create policy suppliers_insert on public.suppliers for insert to authenticated with check (public.has_role(array['manager', 'operations', 'finance']));
create policy suppliers_update on public.suppliers for update to authenticated using (public.has_role(array['manager', 'operations', 'finance'])) with check (public.has_role(array['manager', 'operations', 'finance']));
create policy suppliers_delete on public.suppliers for delete to authenticated using (public.has_role(array['manager']));

alter table public.purchases enable row level security;
revoke all on public.purchases from anon;
grant select, insert, update, delete on public.purchases to authenticated;
drop policy if exists purchases_select on public.purchases;
drop policy if exists purchases_insert on public.purchases;
drop policy if exists purchases_update on public.purchases;
drop policy if exists purchases_delete on public.purchases;
create policy purchases_select on public.purchases for select to authenticated using (public.has_role(array['manager', 'finance', 'hr', 'sales', 'operations']));
create policy purchases_insert on public.purchases for insert to authenticated with check (public.has_role(array['manager', 'operations', 'finance']));
create policy purchases_update on public.purchases for update to authenticated using (public.has_role(array['manager', 'operations', 'finance'])) with check (public.has_role(array['manager', 'operations', 'finance']));
create policy purchases_delete on public.purchases for delete to authenticated using (public.has_role(array['manager', 'finance']));

alter table public.employees enable row level security;
revoke all on public.employees from anon;
grant select, insert, update, delete on public.employees to authenticated;
drop policy if exists employees_select on public.employees;
drop policy if exists employees_insert on public.employees;
drop policy if exists employees_update on public.employees;
drop policy if exists employees_delete on public.employees;
create policy employees_select on public.employees for select to authenticated using (public.has_role(array['manager', 'hr', 'operations', 'supervisor', 'finance']));
create policy employees_insert on public.employees for insert to authenticated with check (public.has_role(array['manager', 'hr']));
create policy employees_update on public.employees for update to authenticated using (public.has_role(array['manager', 'hr'])) with check (public.has_role(array['manager', 'hr']));
create policy employees_delete on public.employees for delete to authenticated using (public.has_role(array['owner']));
-- Sensitive columns (id_number, passport_no, date_of_birth, address, next_of_kin, pay_basis, pay_rate, bank_name, bank_account) are only returned to owner, admin, manager, hr, finance: they are left out of the
-- column grant below and served by the view public.employees_sensitive (row filter on the role).
revoke select on public.employees from authenticated;
grant select (id, created_at, created_by, created_by_name, updated_at, updated_by, updated_by_name, deleted_at, deleted_by, deleted_by_name, _src, _seed, data, employee_no, full_name, first_name, last_name, known_as, aliases, gender, phone, email, position, department, employment_type, start_date, end_date, status, reason_for_leaving, ppe_returned, crew_id, is_driver, profile_id, photo_file_id, notes) on public.employees to authenticated;
create or replace view public.employees_sensitive with (security_barrier = true) as
  select id, id_number, passport_no, date_of_birth, address, next_of_kin, pay_basis, pay_rate, bank_name, bank_account from public.employees where public.has_role(array['manager', 'hr', 'finance']);
revoke all on public.employees_sensitive from public, anon;
grant select on public.employees_sensitive to authenticated;

alter table public.payroll enable row level security;
revoke all on public.payroll from anon;
grant select, insert, update, delete on public.payroll to authenticated;
drop policy if exists payroll_select on public.payroll;
drop policy if exists payroll_insert on public.payroll;
drop policy if exists payroll_update on public.payroll;
drop policy if exists payroll_delete on public.payroll;
create policy payroll_select on public.payroll for select to authenticated using (public.has_role(array['manager', 'finance', 'hr']));
create policy payroll_insert on public.payroll for insert to authenticated with check (public.has_role(array['manager', 'finance', 'hr']));
create policy payroll_update on public.payroll for update to authenticated using (public.has_role(array['manager', 'finance', 'hr'])) with check (public.has_role(array['manager', 'finance', 'hr']));
create policy payroll_delete on public.payroll for delete to authenticated using (public.has_role(array['manager', 'finance']));

alter table public.deductions enable row level security;
revoke all on public.deductions from anon;
grant select, insert, update, delete on public.deductions to authenticated;
drop policy if exists deductions_select on public.deductions;
drop policy if exists deductions_insert on public.deductions;
drop policy if exists deductions_update on public.deductions;
drop policy if exists deductions_delete on public.deductions;
create policy deductions_select on public.deductions for select to authenticated using (public.has_role(array['manager', 'finance', 'hr']));
create policy deductions_insert on public.deductions for insert to authenticated with check (public.has_role(array['manager', 'finance', 'hr']));
create policy deductions_update on public.deductions for update to authenticated using (public.has_role(array['manager', 'finance', 'hr'])) with check (public.has_role(array['manager', 'finance', 'hr']));
create policy deductions_delete on public.deductions for delete to authenticated using (public.has_role(array['manager', 'finance']));

alter table public.certificates enable row level security;
revoke all on public.certificates from anon;
grant select, insert, update, delete on public.certificates to authenticated;
drop policy if exists certificates_select on public.certificates;
drop policy if exists certificates_insert on public.certificates;
drop policy if exists certificates_update on public.certificates;
drop policy if exists certificates_delete on public.certificates;
create policy certificates_select on public.certificates for select to authenticated using (public.has_role(array['manager', 'hr', 'operations', 'supervisor']));
create policy certificates_insert on public.certificates for insert to authenticated with check (public.has_role(array['manager', 'hr', 'operations']));
create policy certificates_update on public.certificates for update to authenticated using (public.has_role(array['manager', 'hr', 'operations'])) with check (public.has_role(array['manager', 'hr', 'operations']));
create policy certificates_delete on public.certificates for delete to authenticated using (public.has_role(array['manager', 'hr']));
-- Sensitive columns (id_number) are only returned to owner, admin, manager, hr: they are left out of the
-- column grant below and served by the view public.certificates_sensitive (row filter on the role).
revoke select on public.certificates from authenticated;
grant select (id, created_at, created_by, created_by_name, updated_at, updated_by, updated_by_name, deleted_at, deleted_by, deleted_by_name, _src, _seed, data, employee_id, person_name, course, course_type, level, provider, accreditation, unit_standards, certificate_no, issue_date, expiry_date, validity_rule, result, file_id, notes) on public.certificates to authenticated;
create or replace view public.certificates_sensitive with (security_barrier = true) as
  select id, id_number from public.certificates where public.has_role(array['manager', 'hr']);
revoke all on public.certificates_sensitive from public, anon;
grant select on public.certificates_sensitive to authenticated;

alter table public.medicals enable row level security;
revoke all on public.medicals from anon;
grant select, insert, update, delete on public.medicals to authenticated;
drop policy if exists medicals_select on public.medicals;
drop policy if exists medicals_insert on public.medicals;
drop policy if exists medicals_update on public.medicals;
drop policy if exists medicals_delete on public.medicals;
create policy medicals_select on public.medicals for select to authenticated using (public.has_role(array['manager', 'hr']));
create policy medicals_insert on public.medicals for insert to authenticated with check (public.has_role(array['manager', 'hr']));
create policy medicals_update on public.medicals for update to authenticated using (public.has_role(array['manager', 'hr'])) with check (public.has_role(array['manager', 'hr']));
create policy medicals_delete on public.medicals for delete to authenticated using (public.has_role(array['manager', 'hr']));

alter table public.appointments enable row level security;
revoke all on public.appointments from anon;
grant select, insert, update, delete on public.appointments to authenticated;
drop policy if exists appointments_select on public.appointments;
drop policy if exists appointments_insert on public.appointments;
drop policy if exists appointments_update on public.appointments;
drop policy if exists appointments_delete on public.appointments;
create policy appointments_select on public.appointments for select to authenticated using (auth.uid() is not null and public.my_role() is not null);
create policy appointments_insert on public.appointments for insert to authenticated with check (public.has_role(array['manager', 'hr', 'operations']));
create policy appointments_update on public.appointments for update to authenticated using (public.has_role(array['manager', 'hr', 'operations'])) with check (public.has_role(array['manager', 'hr', 'operations']));
create policy appointments_delete on public.appointments for delete to authenticated using (public.has_role(array['manager', 'hr']));

alter table public.incidents enable row level security;
revoke all on public.incidents from anon;
grant select, insert, update, delete on public.incidents to authenticated;
drop policy if exists incidents_select on public.incidents;
drop policy if exists incidents_insert on public.incidents;
drop policy if exists incidents_update on public.incidents;
drop policy if exists incidents_delete on public.incidents;
create policy incidents_select on public.incidents for select to authenticated using (auth.uid() is not null and public.my_role() is not null);
create policy incidents_insert on public.incidents for insert to authenticated with check (auth.uid() is not null and public.my_role() is not null);
create policy incidents_update on public.incidents for update to authenticated using (auth.uid() is not null and public.my_role() is not null) with check (auth.uid() is not null and public.my_role() is not null);
create policy incidents_delete on public.incidents for delete to authenticated using (public.has_role(array['manager', 'hr']));

alter table public.ppe_issues enable row level security;
revoke all on public.ppe_issues from anon;
grant select, insert, update, delete on public.ppe_issues to authenticated;
drop policy if exists ppe_issues_select on public.ppe_issues;
drop policy if exists ppe_issues_insert on public.ppe_issues;
drop policy if exists ppe_issues_update on public.ppe_issues;
drop policy if exists ppe_issues_delete on public.ppe_issues;
create policy ppe_issues_select on public.ppe_issues for select to authenticated using (public.has_role(array['manager', 'hr', 'operations', 'supervisor']));
create policy ppe_issues_insert on public.ppe_issues for insert to authenticated with check (public.has_role(array['manager', 'hr', 'operations', 'supervisor']));
create policy ppe_issues_update on public.ppe_issues for update to authenticated using (public.has_role(array['manager', 'hr', 'operations', 'supervisor'])) with check (public.has_role(array['manager', 'hr', 'operations', 'supervisor']));
create policy ppe_issues_delete on public.ppe_issues for delete to authenticated using (public.has_role(array['manager', 'hr']));

alter table public.hr_actions enable row level security;
revoke all on public.hr_actions from anon;
grant select, insert, update, delete on public.hr_actions to authenticated;
drop policy if exists hr_actions_select on public.hr_actions;
drop policy if exists hr_actions_insert on public.hr_actions;
drop policy if exists hr_actions_update on public.hr_actions;
drop policy if exists hr_actions_delete on public.hr_actions;
create policy hr_actions_select on public.hr_actions for select to authenticated using (public.has_role(array['manager', 'hr']));
create policy hr_actions_insert on public.hr_actions for insert to authenticated with check (public.has_role(array['manager', 'hr']));
create policy hr_actions_update on public.hr_actions for update to authenticated using (public.has_role(array['manager', 'hr'])) with check (public.has_role(array['manager', 'hr']));
create policy hr_actions_delete on public.hr_actions for delete to authenticated using (public.has_role(array['manager', 'hr']));

alter table public.toolbox_talks enable row level security;
revoke all on public.toolbox_talks from anon;
grant select, insert, update, delete on public.toolbox_talks to authenticated;
drop policy if exists toolbox_talks_select on public.toolbox_talks;
drop policy if exists toolbox_talks_insert on public.toolbox_talks;
drop policy if exists toolbox_talks_update on public.toolbox_talks;
drop policy if exists toolbox_talks_delete on public.toolbox_talks;
create policy toolbox_talks_select on public.toolbox_talks for select to authenticated using (auth.uid() is not null and public.my_role() is not null);
create policy toolbox_talks_insert on public.toolbox_talks for insert to authenticated with check (public.has_role(array['manager', 'operations', 'supervisor', 'hr']));
create policy toolbox_talks_update on public.toolbox_talks for update to authenticated using (public.has_role(array['manager', 'operations', 'supervisor', 'hr'])) with check (public.has_role(array['manager', 'operations', 'supervisor', 'hr']));
create policy toolbox_talks_delete on public.toolbox_talks for delete to authenticated using (public.has_role(array['manager', 'hr']));

alter table public.compliance_docs enable row level security;
revoke all on public.compliance_docs from anon;
grant select, insert, update, delete on public.compliance_docs to authenticated;
drop policy if exists compliance_docs_select on public.compliance_docs;
drop policy if exists compliance_docs_insert on public.compliance_docs;
drop policy if exists compliance_docs_update on public.compliance_docs;
drop policy if exists compliance_docs_delete on public.compliance_docs;
create policy compliance_docs_select on public.compliance_docs for select to authenticated using (public.has_role(array['manager', 'finance', 'hr', 'sales', 'operations']));
create policy compliance_docs_insert on public.compliance_docs for insert to authenticated with check (public.has_role(array['manager', 'finance', 'hr']));
create policy compliance_docs_update on public.compliance_docs for update to authenticated using (public.has_role(array['manager', 'finance', 'hr'])) with check (public.has_role(array['manager', 'finance', 'hr']));
create policy compliance_docs_delete on public.compliance_docs for delete to authenticated using (public.has_role(array['manager']));

alter table public.expenses enable row level security;
revoke all on public.expenses from anon;
grant select, insert, update, delete on public.expenses to authenticated;
drop policy if exists expenses_select on public.expenses;
drop policy if exists expenses_insert on public.expenses;
drop policy if exists expenses_update on public.expenses;
drop policy if exists expenses_delete on public.expenses;
create policy expenses_select on public.expenses for select to authenticated using (public.has_role(array['manager', 'finance']));
create policy expenses_insert on public.expenses for insert to authenticated with check (public.has_role(array['manager', 'finance']));
create policy expenses_update on public.expenses for update to authenticated using (public.has_role(array['manager', 'finance'])) with check (public.has_role(array['manager', 'finance']));
create policy expenses_delete on public.expenses for delete to authenticated using (public.has_role(array['manager', 'finance']));

alter table public.financial_periods enable row level security;
revoke all on public.financial_periods from anon;
grant select, insert, update, delete on public.financial_periods to authenticated;
drop policy if exists financial_periods_select on public.financial_periods;
drop policy if exists financial_periods_insert on public.financial_periods;
drop policy if exists financial_periods_update on public.financial_periods;
drop policy if exists financial_periods_delete on public.financial_periods;
create policy financial_periods_select on public.financial_periods for select to authenticated using (public.has_role(array['manager', 'finance']));
create policy financial_periods_insert on public.financial_periods for insert to authenticated with check (public.has_role(array['manager', 'finance']));
create policy financial_periods_update on public.financial_periods for update to authenticated using (public.has_role(array['manager', 'finance'])) with check (public.has_role(array['manager', 'finance']));
create policy financial_periods_delete on public.financial_periods for delete to authenticated using (public.has_role(array['owner']));

alter table public.owner_funding enable row level security;
revoke all on public.owner_funding from anon;
grant select, insert, update, delete on public.owner_funding to authenticated;
drop policy if exists owner_funding_select on public.owner_funding;
drop policy if exists owner_funding_insert on public.owner_funding;
drop policy if exists owner_funding_update on public.owner_funding;
drop policy if exists owner_funding_delete on public.owner_funding;
create policy owner_funding_select on public.owner_funding for select to authenticated using (public.has_role(array['manager', 'finance']));
create policy owner_funding_insert on public.owner_funding for insert to authenticated with check (public.has_role(array['manager', 'finance']));
create policy owner_funding_update on public.owner_funding for update to authenticated using (public.has_role(array['manager', 'finance'])) with check (public.has_role(array['manager', 'finance']));
create policy owner_funding_delete on public.owner_funding for delete to authenticated using (public.has_role(array['owner']));

alter table public.bank_accounts enable row level security;
revoke all on public.bank_accounts from anon;
grant select, insert, update, delete on public.bank_accounts to authenticated;
drop policy if exists bank_accounts_select on public.bank_accounts;
drop policy if exists bank_accounts_insert on public.bank_accounts;
drop policy if exists bank_accounts_update on public.bank_accounts;
drop policy if exists bank_accounts_delete on public.bank_accounts;
create policy bank_accounts_select on public.bank_accounts for select to authenticated using (public.has_role(array['manager', 'finance', 'hr', 'sales', 'operations', 'supervisor']));
create policy bank_accounts_insert on public.bank_accounts for insert to authenticated with check (public.has_role(array['manager', 'finance']));
create policy bank_accounts_update on public.bank_accounts for update to authenticated using (public.has_role(array['manager', 'finance'])) with check (public.has_role(array['manager', 'finance']));
create policy bank_accounts_delete on public.bank_accounts for delete to authenticated using (public.has_role(array['owner']));

alter table public.kpi_definitions enable row level security;
revoke all on public.kpi_definitions from anon;
grant select, insert, update, delete on public.kpi_definitions to authenticated;
drop policy if exists kpi_definitions_select on public.kpi_definitions;
drop policy if exists kpi_definitions_insert on public.kpi_definitions;
drop policy if exists kpi_definitions_update on public.kpi_definitions;
drop policy if exists kpi_definitions_delete on public.kpi_definitions;
create policy kpi_definitions_select on public.kpi_definitions for select to authenticated using (auth.uid() is not null and public.my_role() is not null);
create policy kpi_definitions_insert on public.kpi_definitions for insert to authenticated with check (public.has_role(array['manager']));
create policy kpi_definitions_update on public.kpi_definitions for update to authenticated using (public.has_role(array['manager'])) with check (public.has_role(array['manager']));
create policy kpi_definitions_delete on public.kpi_definitions for delete to authenticated using (public.has_role(array['manager']));

alter table public.kpi_entries enable row level security;
revoke all on public.kpi_entries from anon;
grant select, insert, update, delete on public.kpi_entries to authenticated;
drop policy if exists kpi_entries_select on public.kpi_entries;
drop policy if exists kpi_entries_insert on public.kpi_entries;
drop policy if exists kpi_entries_update on public.kpi_entries;
drop policy if exists kpi_entries_delete on public.kpi_entries;
create policy kpi_entries_select on public.kpi_entries for select to authenticated using (auth.uid() is not null and public.my_role() is not null);
create policy kpi_entries_insert on public.kpi_entries for insert to authenticated with check (public.has_role(array['manager', 'sales', 'operations', 'finance', 'hr']));
create policy kpi_entries_update on public.kpi_entries for update to authenticated using (public.has_role(array['manager', 'sales', 'operations', 'finance', 'hr'])) with check (public.has_role(array['manager', 'sales', 'operations', 'finance', 'hr']));
create policy kpi_entries_delete on public.kpi_entries for delete to authenticated using (public.has_role(array['manager']));

alter table public.goals enable row level security;
revoke all on public.goals from anon;
grant select, insert, update, delete on public.goals to authenticated;
drop policy if exists goals_select on public.goals;
drop policy if exists goals_insert on public.goals;
drop policy if exists goals_update on public.goals;
drop policy if exists goals_delete on public.goals;
create policy goals_select on public.goals for select to authenticated using (public.has_role(array['manager', 'finance', 'hr', 'sales', 'operations']));
create policy goals_insert on public.goals for insert to authenticated with check (public.has_role(array['manager', 'sales', 'operations', 'finance', 'hr']));
create policy goals_update on public.goals for update to authenticated using (public.has_role(array['manager', 'sales', 'operations', 'finance', 'hr'])) with check (public.has_role(array['manager', 'sales', 'operations', 'finance', 'hr']));
create policy goals_delete on public.goals for delete to authenticated using (public.has_role(array['manager']));

alter table public.meetings enable row level security;
revoke all on public.meetings from anon;
grant select, insert, update, delete on public.meetings to authenticated;
drop policy if exists meetings_select on public.meetings;
drop policy if exists meetings_insert on public.meetings;
drop policy if exists meetings_update on public.meetings;
drop policy if exists meetings_delete on public.meetings;
create policy meetings_select on public.meetings for select to authenticated using (public.has_role(array['manager', 'finance', 'hr', 'sales', 'operations', 'supervisor']));
create policy meetings_insert on public.meetings for insert to authenticated with check (public.has_role(array['manager', 'finance', 'hr', 'sales', 'operations']));
create policy meetings_update on public.meetings for update to authenticated using (public.has_role(array['manager', 'finance', 'hr', 'sales', 'operations'])) with check (public.has_role(array['manager', 'finance', 'hr', 'sales', 'operations']));
create policy meetings_delete on public.meetings for delete to authenticated using (public.has_role(array['manager']));

alter table public.design_options enable row level security;
revoke all on public.design_options from anon;
grant select, insert, update, delete on public.design_options to authenticated;
drop policy if exists design_options_select on public.design_options;
drop policy if exists design_options_insert on public.design_options;
drop policy if exists design_options_update on public.design_options;
drop policy if exists design_options_delete on public.design_options;
create policy design_options_select on public.design_options for select to authenticated using (auth.uid() is not null and public.my_role() is not null);
create policy design_options_insert on public.design_options for insert to authenticated with check (public.has_role(array['manager', 'sales']));
create policy design_options_update on public.design_options for update to authenticated using (public.has_role(array['manager', 'sales'])) with check (public.has_role(array['manager', 'sales']));
create policy design_options_delete on public.design_options for delete to authenticated using (public.has_role(array['manager']));

alter table public."references" enable row level security;
revoke all on public."references" from anon;
grant select, insert, update, delete on public."references" to authenticated;
drop policy if exists references_select on public."references";
drop policy if exists references_insert on public."references";
drop policy if exists references_update on public."references";
drop policy if exists references_delete on public."references";
create policy references_select on public."references" for select to authenticated using (auth.uid() is not null and public.my_role() is not null);
create policy references_insert on public."references" for insert to authenticated with check (public.has_role(array['manager', 'sales']));
create policy references_update on public."references" for update to authenticated using (public.has_role(array['manager', 'sales'])) with check (public.has_role(array['manager', 'sales']));
create policy references_delete on public."references" for delete to authenticated using (public.has_role(array['manager']));

alter table public.agent_runs enable row level security;
revoke all on public.agent_runs from anon;
grant select, insert, update, delete on public.agent_runs to authenticated;
drop policy if exists agent_runs_select on public.agent_runs;
drop policy if exists agent_runs_insert on public.agent_runs;
drop policy if exists agent_runs_update on public.agent_runs;
drop policy if exists agent_runs_delete on public.agent_runs;
create policy agent_runs_select on public.agent_runs for select to authenticated using (public.has_role(array['manager', 'operations', 'finance']));
create policy agent_runs_insert on public.agent_runs for insert to authenticated with check (auth.uid() is not null and public.my_role() is not null);
create policy agent_runs_update on public.agent_runs for update to authenticated using (auth.uid() is not null and public.my_role() is not null) with check (auth.uid() is not null and public.my_role() is not null);
create policy agent_runs_delete on public.agent_runs for delete to authenticated using (public.has_role(array['manager']));

alter table public.agent_decisions enable row level security;
revoke all on public.agent_decisions from anon;
grant select, insert, update, delete on public.agent_decisions to authenticated;
drop policy if exists agent_decisions_select on public.agent_decisions;
drop policy if exists agent_decisions_insert on public.agent_decisions;
drop policy if exists agent_decisions_update on public.agent_decisions;
drop policy if exists agent_decisions_delete on public.agent_decisions;
create policy agent_decisions_select on public.agent_decisions for select to authenticated using (public.has_role(array['manager', 'operations', 'finance', 'sales']));
create policy agent_decisions_insert on public.agent_decisions for insert to authenticated with check (auth.uid() is not null and public.my_role() is not null);
create policy agent_decisions_update on public.agent_decisions for update to authenticated using (auth.uid() is not null and public.my_role() is not null) with check (auth.uid() is not null and public.my_role() is not null);
create policy agent_decisions_delete on public.agent_decisions for delete to authenticated using (public.has_role(array['manager']));

alter table public.briefings enable row level security;
revoke all on public.briefings from anon;
grant select, insert, update, delete on public.briefings to authenticated;
drop policy if exists briefings_select on public.briefings;
drop policy if exists briefings_insert on public.briefings;
drop policy if exists briefings_update on public.briefings;
drop policy if exists briefings_delete on public.briefings;
create policy briefings_select on public.briefings for select to authenticated using (public.has_role(array['manager', 'operations', 'finance', 'sales', 'hr']));
create policy briefings_insert on public.briefings for insert to authenticated with check (auth.uid() is not null and public.my_role() is not null);
create policy briefings_update on public.briefings for update to authenticated using (auth.uid() is not null and public.my_role() is not null) with check (auth.uid() is not null and public.my_role() is not null);
create policy briefings_delete on public.briefings for delete to authenticated using (public.has_role(array['manager']));

alter table public.outbox enable row level security;
revoke all on public.outbox from anon;
grant select, insert, update, delete on public.outbox to authenticated;
drop policy if exists outbox_select on public.outbox;
drop policy if exists outbox_insert on public.outbox;
drop policy if exists outbox_update on public.outbox;
drop policy if exists outbox_delete on public.outbox;
create policy outbox_select on public.outbox for select to authenticated using (public.has_role(array['manager', 'finance', 'hr', 'sales', 'operations']));
create policy outbox_insert on public.outbox for insert to authenticated with check (auth.uid() is not null and public.my_role() is not null);
create policy outbox_update on public.outbox for update to authenticated using (auth.uid() is not null and public.my_role() is not null) with check (auth.uid() is not null and public.my_role() is not null);
create policy outbox_delete on public.outbox for delete to authenticated using (public.has_role(array['manager']));

alter table public.data_issues enable row level security;
revoke all on public.data_issues from anon;
grant select, insert, update, delete on public.data_issues to authenticated;
drop policy if exists data_issues_select on public.data_issues;
drop policy if exists data_issues_insert on public.data_issues;
drop policy if exists data_issues_update on public.data_issues;
drop policy if exists data_issues_delete on public.data_issues;
create policy data_issues_select on public.data_issues for select to authenticated using (public.has_role(array['manager', 'finance', 'hr', 'sales', 'operations']));
create policy data_issues_insert on public.data_issues for insert to authenticated with check (public.has_role(array['manager', 'finance', 'hr', 'sales', 'operations']));
create policy data_issues_update on public.data_issues for update to authenticated using (public.has_role(array['manager', 'finance', 'hr', 'sales', 'operations'])) with check (public.has_role(array['manager', 'finance', 'hr', 'sales', 'operations']));
create policy data_issues_delete on public.data_issues for delete to authenticated using (public.has_role(array['manager']));

-- audit_log is append-only for everyone (written by trigger only)
revoke insert, update, delete on public.audit_log from authenticated;
