-- =============================================================================
-- Landscapers Inc. HQ — storage buckets + policies
-- GENERATED by tools/gen-sql.mjs from js/schema/*.js — do not edit by hand.
-- =============================================================================

insert into storage.buckets (id, name, public, file_size_limit) values ('drive', 'drive', false, 52428800) on conflict (id) do nothing;
insert into storage.buckets (id, name, public, file_size_limit) values ('avatars', 'avatars', false, 5242880) on conflict (id) do nothing;

drop policy if exists drive_read on storage.objects;
drop policy if exists drive_write on storage.objects;
drop policy if exists drive_update on storage.objects;
drop policy if exists drive_delete on storage.objects;
-- A stored document is readable only by people who can see its record in public.files (the files policy — confidential
-- flag, restricted drives — applies inside this check) or who uploaded it. Profile pictures are readable by all staff.
create policy drive_read   on storage.objects for select to authenticated using (public.my_role() is not null and (
  bucket_id = 'avatars' or (bucket_id = 'drive' and (owner = auth.uid() or exists (select 1 from public.files f where f.storage_path = storage.objects.name)))));
-- uploads go to "<drive id>/<file id>/<name>": nobody writes into a restricted drive they cannot open
create policy drive_write  on storage.objects for insert to authenticated with check (bucket_id in ('drive','avatars') and public.my_role() is not null and public.my_role() <> 'viewer'
  and (bucket_id = 'avatars' or public.can_see_drive(split_part(name, '/', 1))));
create index if not exists files_storage_path_idx on public.files (storage_path);
create policy drive_update on storage.objects for update to authenticated using (bucket_id in ('drive','avatars') and (owner = auth.uid() or public.has_role(array['manager'])));
create policy drive_delete on storage.objects for delete to authenticated using (bucket_id in ('drive','avatars') and (owner = auth.uid() or public.has_role(array['manager'])));
